import 'package:flutter/animation.dart';
import 'package:flutter/material.dart';

AlertDialog scoretable(BuildContext context) {
  return AlertDialog(
    contentPadding: const EdgeInsets.fromLTRB(0, 2, 0, 1),
    contentTextStyle: TextStyle(height: 2, color: Colors.black),
    title: Text('Scoreboard'),
    content: Container(
      width: 700,
      color: Colors.transparent,
//        height: 70,
//        padding: const EdgeInsets.all(20),
//        margin: const EdgeInsets.only(top: 5),
//      decoration: BoxDecoration(
////          color: Colors.white,
//        boxShadow: <BoxShadow>[
//          BoxShadow(
//            color: Colors.grey[300],
////              blurRadius: 3,
////              spreadRadius: 6,
//          )
//        ],
//      ),
      child: Table(
        defaultColumnWidth: FlexColumnWidth(6.0),
        border: TableBorder.all(width: 0.9, color: Colors.black),
        columnWidths: {
          0: FractionColumnWidth(.05),
          1: FractionColumnWidth(.10),
          2: FractionColumnWidth(.06),
          3: FractionColumnWidth(.10),
          4: FractionColumnWidth(.06),
          5: FractionColumnWidth(.10),
          6: FractionColumnWidth(.06),
          7: FractionColumnWidth(.10),
          8: FractionColumnWidth(.06),
          9: FractionColumnWidth(.10),
          10: FractionColumnWidth(.06),
          11: FractionColumnWidth(.10),
          12: FractionColumnWidth(.06),
        },
        children: [
          TableRow(children: [
            //0
            Text(""),
            Text("Uno"),
            Text("UB"),//UnoBet
            Text("Dos"),
            Text("DB"), //DosBet
            Text("Tres"),
            Text("TB"), //TresBet
            Text("Quat"), //Quatro
            Text("QB"), //QuatroBet
            Text("Cinc"), //Cinco
            Text("CB"), //CincoBet
            Text("Seis"),
            Text("SB"), //SeisBet
          ]),
          TableRow(children: [
            //1
            Text("1"),
            Text("Uno"),
            Text(""),
            Text("Dos"),
            Text(""),
            Text("Tres"),
            Text(""),
            Text("Quat"),
            Text(""),
            Text("Cinc"),
            Text(""),
            Text("Seis"),
            Text(""),
          ]),
          TableRow(children: [
            //2
            Text("2"),
            Text("Uno"),
            Text(""),
            Text("Dos"),
            Text(""),
            Text("Tres"),
            Text(""),
            Text("Quat"),
            Text(""),
            Text("Cinc"),
            Text(""),
            Text("Seis"),
            Text(""),
          ]),
          TableRow(children: [
            //3
            Text("3"),
            Text("Uno"),
            Text(""),
            Text("Dos"),
            Text(""),
            Text("Tres"),
            Text(""),
            Text("Quat"),
            Text(""),
            Text("Cinc"),
            Text(""),
            Text("Seis"),
            Text(""),
          ]),
          TableRow(children: [
            //4
            Text("4"),
            Text("Uno"),
            Text(""),
            Text("Dos"),
            Text(""),
            Text("Tres"),
            Text(""),
            Text("Quat"),
            Text(""),
            Text("Cinc"),
            Text(""),
            Text("Seis"),
            Text(""),
          ]),
          TableRow(children: [
            //5
            Text("5"),
            Text("Uno"),
            Text(""),
            Text("Dos"),
            Text(""),
            Text("Tres"),
            Text(""),
            Text("Quat"),
            Text(""),
            Text("Cinc"),
            Text(""),
            Text("Seis"),
            Text(""),
          ]),
          TableRow(children: [
            //6
            Text("6"),
            Text("Uno"),
            Text(""),
            Text("Dos"),
            Text(""),
            Text("Tres"),
            Text(""),
            Text("Quat"),
            Text(""),
            Text("Cinc"),
            Text(""),
            Text("Seis"),
            Text(""),
          ]),
          TableRow(children: [
            //7
            Text("7"),
            Text("Uno"),
            Text(""),
            Text("Dos"),
            Text(""),
            Text("Tres"),
            Text(""),
            Text("Quat"),
            Text(""),
            Text("Cinc"),
            Text(""),
            Text("Seis"),
            Text(""),
          ]),
          TableRow(children: [
            //8
            Text("8"),
            Text("Uno"),
            Text(""),
            Text("Dos"),
            Text(""),
            Text("Tres"),
            Text(""),
            Text("Quat"),
            Text(""),
            Text("Cinc"),
            Text(""),
            Text("Seis"),
            Text(""),
          ]),
          TableRow(children: [
            //9
            Text("9"),
            Text("Uno"),
            Text(""),
            Text("Dos"),
            Text(""),
            Text("Tres"),
            Text(""),
            Text("Quat"),
            Text(""),
            Text("Cinc"),
            Text(""),
            Text("Seis"),
            Text(""),
          ]),
          TableRow(children: [
            //10
            Text("10"),
            Text("Uno"),
            Text(""),
            Text("Dos"),
            Text(""),
            Text("Tres"),
            Text(""),
            Text("Quat"),
            Text(""),
            Text("Cinc"),
            Text(""),
            Text("Seis"),
            Text(""),
          ]),
          TableRow(children: [
            //11
            Text("11"),
            Text("Uno"),
            Text(""),
            Text("Dos"),
            Text(""),
            Text("Tres"),
            Text(""),
            Text("Quat"),
            Text(""),
            Text("Cinc"),
            Text(""),
            Text(""),
            Text(""),
          ]),
          TableRow(children: [
            //12
            Text("12"),
            Text("Uno"),
            Text(""),
            Text("Dos"),
            Text(""),
            Text("Tres"),
            Text(""),
            Text("Quat"),
            Text(""),
            Text("Cinc"),
            Text(""),
            Text(""),
            Text(""),
          ]),
          TableRow(children: [
            //13
            Text("13"),
            Text("Uno"),
            Text(""),
            Text("Dos"),
            Text(""),
            Text("Tres"),
            Text(""),
            Text("Quat"),
            Text(""),
            Text(""),
            Text(""),
            Text(""),
            Text(""),
          ]),
          TableRow(children: [
            //14
            Text("14"),
            Text("Uno"),
            Text(""),
            Text("Dos"),
            Text(""),
            Text("Tres"),
            Text(""),
            Text("Quat"),
            Text(""),
            Text(""),
            Text(""),
            Text(""),
            Text(""),
          ]),
          TableRow(children: [
            //15
            Text("15"),
            Text("Uno"),
            Text(""),
            Text("Dos"),
            Text(""),
            Text("Tres"),
            Text(""),
            Text("Quat"),
            Text(""),
            Text(""),
            Text(""),
            Text(""),
            Text(""),
          ]),
          TableRow(children: [
            //16
            Text("16"),
            Text("Uno"),
            Text(""),
            Text("Dos"),
            Text(""),
            Text("Tres"),
            Text(""),
            Text(""),
            Text(""),
            Text(""),
            Text(""),
            Text(""),
            Text(""),
          ]),
          TableRow(children: [
            //17
            Text("17"),
            Text("Uno"),
            Text(""),
            Text("Dos"),
            Text(""),
            Text("Tres"),
            Text(""),
            Text(""),
            Text(""),
            Text(""),
            Text(""),
            Text(""),
            Text(""),
          ]),
          TableRow(children: [
            //18
            Text("18"),
            Text("Uno"),
            Text(""),
            Text("Dos"),
            Text(""),
            Text("Tres"),
            Text(""),
            Text(""),
            Text(""),
            Text(""),
            Text(""),
            Text(""),
            Text(""),
          ]),
          TableRow(children: [
            //19
            Text("19"),
            Text("Uno"),
            Text(""),
            Text("Dos"),
            Text(""),
            Text("Tres"),
            Text(""),
            Text(""),
            Text(""),
            Text(""),
            Text(""),
            Text(""),
            Text(""),
          ]),
          TableRow(children: [
            //20
            Text("20"),
            Text("Uno"),
            Text(""),
            Text("Dos"),
            Text(""),
            Text("Tres"),
            Text(""),
            Text(""),
            Text(""),
            Text(""),
            Text(""),
            Text(""),
            Text(""),
          ]),
        ],
      ),
    ),
  );
}
